server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    # This server does not need to register with itself or fetch a registry
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
